apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  creationTimestamp: "2024-11-10T16:14:44Z"
  name: jenkins-service
  namespace: ci-cd
  resourceVersion: "5065"
  uid: 2063d7e1-db6e-4385-86cc-2bf543ec860a
spec:
  clusterIP: 10.109.68.241
  clusterIPs:
  - 10.109.68.241
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 32000
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: agent
    nodePort: 32001
    port: 50000
    targetPort: 50000
    protocol: TCP
  selector:
    app: jenkins-server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

